### PR TITLE
Add a button to copy the image in the image tag format

### PR DESCRIPTION
**Pull request by pmahnke**
## Done 

- Add a button to copy the image in the image tag format
- **NOTE - you can see the output in an alert, but I can't get it to the clipboard - please help**

## QA

1. Download and run this branch
2. Go to http://0.0.0.0:8018/?q=451&type=
3. Click on 'Image tag'
4. See the alert, and know it should be in the clipboard, also formatted more nicely for extra points

## Screenshot

image

### CODE REVIEW

**Comment by anthonydillon** [comment]
I would suggest giving the new button a unique class and attaching a new function that doesn't try to load the image path but just injects the image tag into the temporary text area.

**Comment by pmahnke** [comment]
either way, I think I will have the issue of the async process and getting
the return out of the scope, no?

**Comment by anthonydillon** [comment]
@pmahnke separated the button handlers to accommodate a callback from the `onload`.

**Comment by anthonydillon** [comment]
@pmahnke do you want to ensure the QA is ok

**Review by pmahnke — COMMENTED** [review]
+1 thanks... I also formated the tag better

**Comment by pmahnke** [comment]
@anthonydillon +1 thanks... I also formated the tag better but I cannot approve

**Comment by anthonydillon** [comment]
Nice :+1:

**Review by anthonydillon — APPROVED** [review]

**Pull request merged**
